language: go

go:
  - tip

before_install:
  - curl https://glide.sh/get | sh

script:
  - glide up
  - go test -race -coverprofile=coverage.txt -covermode=atomic -v ./calculator
  - go test -race -coverprofile=coverage.txt -covermode=atomic -v ./xmlbuilder

after_success:
  - bash <(curl -s https://codecov.io/bash)

sudo: false