language: go

go:
  - tip

before_install:
  - curl https://glide.sh/get | sh

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic -v ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)

sudo: false