language: go

go:
  - 1.8.x
  - tip

before_install:
  - sudo apt-get install curl -qq
  - curl https://glide.sh/get | sh
  - glide up

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)

sudo: enabled